[project]
name = "nix-config"
revision = "1.0"

[profiles.default]
GITHUB_TOKEN = { description = "GitHub PAT (Classic or Fine-grained) to avoid Nix rate limits", required = true }
NIX_CONFIG = { description = "Injected Nix config", composed = "access-tokens = github.com=${GITHUB_TOKEN}" }
