# treefmt.nix
{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";
  programs = {
    nixfmt.enable = true;
    yamlfmt.enable = true;
    prettier = {
      enable = true;
      includes = [ "*.md" ];
    };
  };
  # Override the default settings generated by the above option
  settings.formatter.prettier.excludes = [ "" ];
  # Override the default settings generated by the above option for all formatter
  settings.global.excludes = [ "" ];
}
