username = "curious"
display_name = "Curious"
email = "Curious@curious.host"
origin = "nest.pijul.com"
last_modified = "2026-08-08T20:24:48.736870583Z"

[public_key]
key = "AAAAC3NzaC1lZDI1NTE5AAAAIC+tr1tdtkWIyEHe7PUHoxTIasBtPn1mtAI2KxSjlvHs"
