stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
# pub keys
keys:
  - &users '':
      - &curious age1x8a36nac7w9fr8ajnng0ft65z2m2uctw6u57tnsvkt8yxjfdlddsrgjr8n
  - &hosts '':
      - &Server-Ideapad-G480 age1eqecl2ayj4huxdr06fzzmzxphfurzdy8gfh60ncc248jfxrsd3es5cf7lj # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *curious
          - *Server-Ideapad-G480
